export const ITEM_LIST_REQUEST = 'ITEM_LIST_REQUEST'
export const ITEM_LIST_SUCCESS = 'ITEM_LIST_SUCCESS'
export const ITEM_LIST_FAIL = 'ITEM_LIST_FAIL'

export const ITEM_DETAILS_REQUEST = 'ITEM_DETAILS_REQUEST'
export const ITEM_DETAILS_SUCCESS = 'ITEM_DETAILS_SUCCESS'
export const ITEM_DETAILS_FAIL = 'ITEM_DETAILS_FAIL'

export const ADD_NEW_ITEM_REQUEST = 'ADD_NEW_ITEM_REQUEST'
export const ADD_NEW_ITEM_SUCCESS = 'ADD_NEW_ITEM_SUCCESS'
export const ADD_NEW_ITEM_FAIL = 'ADD_NEW_ITEM_FAIL'

export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST'
export const UPDATE_ITEM_SUCCESS = 'ADD_NEW_ITEM_SUCCESS'
export const UPDATE_ITEM_FAIL = 'ADD_NEW_ITEM_FAIL'