export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_CONSTANT'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_ITEMS_LIST_REQUEST = 'RESTAURANT_ITEMS_LIST_CONSTANT'
export const RESTAURANT_ITEMS_LIST_SUCCESS = 'RESTAURANT_ITEMS_LIST_SUCCESS'
export const RESTAURANT_ITEMS_LIST_FAIL = 'RESTAURANT_ITEMS_LIST_FAIL'

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST'
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS'
export const RESTAURANT_REGISTER_FAIL = 'RESTAURANT_REGISTER_FAIL'
export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT'

export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST'
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS'
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL'

export const RESTAURANT_DETAILS_REQUEST = 'RESTAURANT_DETAILS_REQUEST'
export const RESTAURANT_DETAILS_SUCCESS = 'RESTAURANT_DETAILS_SUCCESS'
export const RESTAURANT_DETAILS_FAIL = 'RESTAURANT_DETAILS_FAIL'
export const RESTAURANT_DETAILS_RESET = 'RESTAURANT_DETAILS_RESET'

export const RESTAURANT_UPDATE_PROFILE_REQUEST = 'RESTAURANT_UPDATE_PROFILE_REQUEST'
export const RESTAURANT_UPDATE_PROFILE_SUCCESS = 'RESTAURANT_UPDATE_PROFILE_SUCCESS'
export const RESTAURANT_UPDATE_PROFILE_FAIL = 'RESTAURANT_UPDATE_PROFILE_FAIL'