export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_CONSTANT'
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS'
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL'

export const RESTAURANT_REGISTER_REQUEST = 'RESTAURANT_REGISTER_REQUEST'
export const RESTAURANT_REGISTER_SUCCESS = 'RESTAURANT_REGISTER_SUCCESS'
export const RESTAURANT_REGISTER_FAIL = 'RESTAURANT_REGISTER_FAIL'
export const RESTAURANT_LOGOUT = 'RESTAURANT_LOGOUT'

export const RESTAURANT_LOGIN_REQUEST = 'RESTAURANT_LOGIN_REQUEST'
export const RESTAURANT_LOGIN_SUCCESS = 'RESTAURANT_LOGIN_SUCCESS'
export const RESTAURANT_LOGIN_FAIL = 'RESTAURANT_LOGIN_FAIL'